export const ERRORCODES = {
  INVALID_CREDENTIALS: 'Invalid email or password',
  INVALID_ENV: 'Invalid environment configuration',
  INTERNAL_ERROR: 'Internal server error',
  UNAUTHORIZED: 'Unauthorized access',
  FORBIDDEN: 'Access forbidden',
  NOT_FOUND: 'Resource not found',
  BAD_REQUEST: 'Bad request',
  UNPROCESSABLE_ENTITY: 'Unprocessable entity',
  CONFLICT: 'Resource conflict',
  SERVICE_UNAVAILABLE: 'Service unavailable',
  GATEWAY_TIMEOUT: 'Gateway timeout',
  UNSUPPORTED_MEDIA_TYPE: 'Unsupported media type',
  NOT_IMPLEMENTED: 'Not implemented',
  BAD_GATEWAY: 'Bad gateway',
  HTTP_VERSION_NOT_SUPPORTED: 'HTTP version not supported',
  LOOP_DETECTED: 'Loop detected',
  NOT_EXTENDED: 'Not extended',
  NETWORK_AUTHENTICATION_REQUIRED: 'Network authentication required',
  NETWORK_CONNECTIVITY_LOST: 'Network connectivity lost',
  NETWORK_READ_TIMEOUT: 'Network read timeout',
  NETWORK_WRITE_TIMEOUT: 'Network write timeout',
  PAYMENT_REQUIRED: 'Payment required',
  PRECONDITION_FAILED: 'Precondition failed',
  PROXY_AUTHENTICATION_REQUIRED: 'Proxy authentication required',
  REQUEST_HEADER_FIELDS_TOO_LARGE: 'Request header fields too large',
  REQUEST_TIMEOUT: 'Request timeout',
  TOO_MANY_REQUESTS: 'Too many requests',
  UNAVAILABLE_FOR_LEGAL_REASONS: 'Unavailable for legal reasons',
  VARIANT_ALSO_NEGOTIATES: 'Variant also negotiates',
  EXPECTATION_FAILED: 'Expectation failed',
  IM_A_TEAPOT: "I'm a teapot",
  INSUFFICIENT_STORAGE: 'Insufficient storage',
};
export const SUCCESS_CODES = {
  MESSAGE_SENT: 'message sent successfully',
  USER_REGISTERED: 'user registered successfully',
};
